name: CI

on:
  push:
  pull_request:
    branches: ["*"]
    tags-ignore: ["**"]

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: swift build

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Swift
        uses: YOCKOW/Action-setup-swift@v1

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt install libavahi-compat-libdnssd-dev

      - name: Build
        run: swift build
